#!/usr/bin/env bash
sudo -v

# Launchpad 图标行列数量更改
defaults write com.apple.dock springboard-rows -int 7
defaults write com.apple.dock springboard-columns -int 10

# Dock
defaults write com.apple.dock tilesize -int 40
defaults write com.apple.dock show-process-indicators -bool true
defaults write com.apple.dock minimize-to-application -bool true
defaults write com.apple.dock show-recents -bool false

# Terminal utf-8
defaults write com.apple.terminal StringEncodings -array 4

# Avoid create DS_Store to USB
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true

killall Dock

sudo spctl --master-disable
