#!/usr/bin/env bash

echo "Setup sdkman"
curl -s "https://get.sdkman.io" | bash

cp -p ./sdkman/config ~/.sdkman/etc/

source "$HOME/.sdkman/bin/sdkman-init.sh"

echo "Setup JDK"
sdk install java 11.0.11.hs-adpt
sdk install java 8.0.292.hs-adpt

echo "Setup Maven"
sdk install maven
