#!/usr/bin/env bash

echo "Setup Zsh"
ZSH_PATH="$(brew --prefix)/bin/zsh"
sudo sh -c "echo $ZSH_PATH >> /etc/shells"
sudo chsh -s $ZSH_PATH
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
cp ./zsh/.zsh_alias ~/
cp ./zsh/.zshrc ~/

echo "Setup Zinit"
sh -c "$(curl -fsSL https://raw.githubusercontent.com/zdharma/zinit/master/doc/install.sh)"

echo "Setup Powerlevel10k"
cp ./zsh/.p10k.zsh ~/
